# Generated by Django 4.0.4 on 2022-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_thumbnail', models.ImageField(blank=True, default='default_thumbnail.jpg', null=True, upload_to='')),
                ('project_image', models.ImageField(blank=True, default='default_project.jpg', null=True, upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.CharField(choices=[('WEB APPS', 'WEB APPS '), ('APIS', 'APIS '), ('STATIC SITE', 'STATIC SITE')], max_length=100)),
                ('date', models.DateField()),
                ('project_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('technologies', models.ManyToManyField(blank=True, to='projects.technology')),
            ],
        ),
    ]
